title: Streamdata Gallery
url: usagov-corporate-consumer-contact-information.api.streamdata.gallery
tag: USA.Gov Corporate Consumer Contact Information
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: usagov-corporate-consumer-contact-information
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
